name: Build and push latest deepforge/worker image

on:
  push:
    branches:
      - master
      - 5-publish-docker-image

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
